### ISSUE TITLE
移动端横屏处理

### ISSUE THREAD

**Issue by heqiang100** [linjc/smooth-signature#10]
有没有横屏的处理方案
现状：现将页面布局后，然后整体旋转变成90度，但签名组件坐标计算会反过来，x变成y，y变成x
![image](https://user-images.githubusercontent.com/7948078/167234032-99707cc8-245b-4154-a94c-38be30964faf.png)

**Comment by linjc** [comment]
@heqiang100 参考样例/example/src/components/mbDemo.vue

**Comment by heqiang100** [comment]
邮件已收到。 熊
