### ISSUE TITLE
能兼容pad端横屏使用吗

### ISSUE THREAD

**Issue by zhangwj0425** [linjc/smooth-signature#11]

**Comment by linjc** [comment]
@zhangwj0425 参考样例/example/src/components/mbDemo.vue

**Comment by linjc** [comment]
@zhangwj0425 其实不用刻意去旋转画布，只设置其宽高就行，最终输出图片的时候，使用signature.getRotateCanvas(degree)获取旋转指定角度的画布，再转成DataURL即可
