### ISSUE TITLE
更新画笔颜色，发现写出来的字包含多种颜色。

### ISSUE THREAD

**Issue by JackySoft** [linjc/smooth-signature#26]
<img width="973" alt="image" src="https://github.com/user-attachments/assets/9d83d709-87f6-485f-91bb-dd07ce0fcaf8">

我目前是在低代码平台中使用，所以，签名的属性不是初始化固定死的，是动态配置的，但是发现修改画笔颜色以后，第二次写的字会包含第一次的画笔颜色。我已经调用了签名的clear方法也无用。甚至调用签名对象获取到ctx，清除canvas画布都没用。

**Comment by linjc** [comment]
@JackySoft 用的最新npm包吗

**Comment by JackySoft** [comment]
"smooth-signature": "^1.0.15"  是最新的版本。直接实例化一次是没问题的，现在的问题时，参数是动态传递的，所以只能实例化一次，监听props变化，动态修改画笔参数。

大概的代码如下：

`const Signature = ({ config }:any, ref: any) => {
  const [visible, setVisible] = useState(true);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const signatureRef = useRef<SmoothSignature | null>(null);

  useEffect(() => {
    if (!canvasRef.current) return;
    // 如果signatureRef已经存在，先清除之前的实例
    if (signatureRef.current) {
      signatureRef.current.clear();
      signatureRef.current = null;
    }
    signatureRef.current = new SmoothSignature(canvasRef.current, config.props);
  }, [config.props]);

  // 对外暴露方法
  useImperativeHandle(ref, () => {
    return {
      getImage(type: string) {
        if (type === 'jpg') {
          return signatureRef.current?.getJPG();
        }
        return signatureRef.current?.getPNG();
      },
      isEmpty() {
        return signatureRef.current?.isEmpty();
      },
      clear() {
        signatureRef.current?.clear();
      },
    };
  });
  return (
      <div>
        <canvas ref={canvasRef}></canvas>
      </div>
  );
};
export default memo(forwardRef(Signature));`

**Comment by linjc** [comment]
@JackySoft 你在重新初始化的时候，先把上一次监听事件销毁掉，signatureRef.current.removeListener()

**Comment by JackySoft** [comment]
ok ，我晚上试试，感谢。
