### ISSUE TITLE
isEmpty() 始终返回 false

### ISSUE THREAD

**Issue by Meqn** [linjc/smooth-signature#5]
您好，SmoothSignature 初始化完调用 `isEmpty()` 就返回 false。

看了下源码，empty()的逻辑是有问题的。

https://github.com/linjc/smooth-signature/blob/d4f3964d7bb703928149ab9df9fb97583246369b/src/index.ts#L349-L359

**Comment by linjc** [comment]
@Meqn 初始化配置是？

**Comment by linjc** [comment]
@Meqn 初始化的配置是？

**Comment by linjc** [comment]
@Meqn :+1: 收到，已修复
