### ISSUE TITLE
希望开放onMove回调

### ISSUE THREAD

**Issue by imaxing** [linjc/smooth-signature#9]
保存轨迹数据
绘制其他图形
轨迹回放
等都需要onmove回调保存轨迹节点进行实现

等大佬发布一个新版本 ~~

**Comment by linjc** [comment]
@imaxing 可自行给canvas添加响应事件实现
canvas.addEventListener('touchmove', moveFn);
canvas.addEventListener('mousemove', moveFn);

**Comment by imaxing** [comment]
@linjc 
这样是可以实现, 但看起来不太友好
并且需要手动解绑事件, 这个参数并非跟业务相关 不算影响大佬的组件功能的~
大佬的组件如此优秀后续肯定还会有其他人遇到此需求的, 可以增加这个参数吗🤣

**Comment by imaxing** [comment]
@linjc 大佬!
我通过自己绑定事件, 可以拿到x,y, 并设置t值,
有轨迹节点数据了但笔锋重新绘制出来我太菜了 搞不定😂
我尝试调用onDraw, onstart都没能有效果, 是不是可以将大佬的绘制核心逻辑抽离出来呢, 比如:

```javascript

// 绘制函数
const drawStart = ({x, y}) => {}
const drawing = ({x, y}) => {}
const drawEnd = () => {}


// 事件绑定伪代码
onTouchStart: e => drawStart({e.x, y: e.y})
onTouchMove: e => drawing({e.x, y: e.y})
onTouchEnd: drawEnd

// 实例调用
const ins = new SmoothSignature(canvas)
axios.get('/api/points').then(points => {
const [{x, y}, ...ps] = points
   ins.drawStart({x, y})
  ps.forEach(({x, y}) => ins.drawing({x, y}))
})
```

**Comment by linjc** [comment]
@imaxing 轨迹是拿取坐标点后通过相关逻辑绘制出来的，并不是具体的数据，坐标点和你监听move事件拿到的坐标是一样的。所以，暂无法支持。
